plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.0' apply false
    id 'maven-publish'
}

allprojects {
    group = 'com.github.mmmq'
    version = '0.0.4-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
        withSourcesJar()
    }

    dependencies {
        implementation platform('org.springframework.boot:spring-boot-dependencies:3.2.0')
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }

    publishing {
        publications {
            maven(MavenPublication) {
                from components.java
            }
        }
    }
}
